# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk13
#\
# используем режим обычного пользователя для сборки проекта.
sudo: false


# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)
  #token from codecov
  env:
    global:
    fd88fb6b-a023-45d0-9703-07a8ff0c8b21
# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      continuousIntegrationReports@list.ru
    on_success: always # default: change or never
    on_failure: always # default: always
#df;slkdf
